name: New York Times

on:
  workflow_dispatch:
  schedule:
    - cron: "30 */4 * * *"

jobs:
  run:
    name: Screenshot
    uses: ./.github/workflows/single.yml
    with:
      source: >-
        ["nytimes"]
    secrets:
      telegram-api-key: ${{ secrets.TELEGRAM_API_KEY }}
      discord-bot-token: ${{ secrets.DISCORD_BOT_TOKEN }}
      twitter-consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      twitter-consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      twitter-access-token-key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
      twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      ia-access-key: ${{ secrets.IA_ACCESS_KEY }}
      ia-secret-key: ${{ secrets.IA_SECRET_KEY }}
      ia-collection: ${{ secrets.IA_COLLECTION }}